image: docker:19.03.8
stages:
  - build
alpine:
  stage: build
  variables:
    VERSION: "3.11"
  script:
    - cd $CI_JOB_NAME
    - docker build -t $REGISTRY_DOMAIN/$CI_JOB_NAME:$VERSION .
    - docker push $REGISTRY_DOMAIN/$CI_JOB_NAME:$VERSION
  only:
    changes:
      - alpine/*

  tags:
    - images
