image: docker:19.03.8
stages:
  - build
alpine_glibc:
  stage: build
  variables:
    VERSION: "2.29"
  script:
    - cd $CI_JOB_NAME
    - docker build -t $REGISTRY_DOMAIN/$CI_JOB_NAME:$VERSION .
    - docker push $REGISTRY_DOMAIN/$CI_JOB_NAME:$VERSION
  only:
    changes:
      - alpine_glibc/*

  tags:
    - images
