image: docker:19.03.8
stages:
  - build

docker:
  stage: build
  variables:
    VERSION: "19.03.8"
  script:
    - cd $CI_JOB_NAME
    - docker build -t $REGISTRY_DOMAIN/$CI_JOB_NAME:$VERSION .
    - docker push $REGISTRY_DOMAIN/$CI_JOB_NAME:$VERSION
  only:
    changes:
      - docker/*

  tags:
    - images
